-- go-pugleaf: Create hierarchies table for efficient Usenet hierarchy navigation

CREATE TABLE IF NOT EXISTS hierarchies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    group_count INTEGER DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_hierarchies_name ON hierarchies(name);
CREATE INDEX IF NOT EXISTS idx_hierarchies_group_count ON hierarchies(group_count);


-- Insert some common Usenet hierarchies with descriptions
INSERT OR IGNORE INTO hierarchies (name, description) VALUES

-- Primary Big 8 hierarchies (alphabetical)
('comp', 'Computer-related discussions and support'),
('humanities', 'Liberal arts and humanities'),
('misc', 'Miscellaneous topics not fitting other categories'),
('news', 'Usenet news and announcements'),
('rec', 'Recreation, hobbies, and entertainment'),
('sci', 'Science and technology discussions'),
('soc', 'Social issues and cultural topics'),
('talk', 'General discussion and debate'),

-- Alternative hierarchies
('alt', 'Alternative discussions and topics'),
('alt.anonymous', 'Anonymous posting groups'),
('alt.binaries', 'Binary file sharing'),
('alt.conspiracy', 'Conspiracy theories'),
('alt.culture', 'Cultural discussions'),
('alt.fan', 'Fan groups for various topics'),
('alt.folklore', 'Folklore and urban legends'),
('alt.humor', 'Humor and jokes'),
('alt.music', 'Music discussions'),
('alt.politics', 'Political discussions'),
('alt.privacy', 'Privacy-related discussions'),
('alt.religion', 'Religious discussions'),
('alt.security', 'Security discussions'),
('alt.sex', 'Adult discussions'),
('alt.society', 'Society and social issues'),

-- Regional/Language hierarchies (alphabetical by code)
('ar', 'Arabic language newsgroups'),
('at', 'Austrian newsgroups'),
('au', 'Australian newsgroups'),
('aus', 'Australian regional groups'),
('be', 'Belgian newsgroups'),
('bg', 'Bulgarian newsgroups'),
('br', 'Brazilian Portuguese newsgroups'),
('ca', 'California regional groups'),
('can', 'Canadian regional groups'),
('ch', 'Swiss newsgroups'),
('cl', 'Chilean newsgroups'),
('cn', 'Chinese language newsgroups'),
('co', 'Colombian newsgroups'),
('cr', 'Costa Rican newsgroups'),
('cz', 'Czech language newsgroups'),
('de', 'German language newsgroups'),
('dk', 'Danish language newsgroups'),
('ee', 'Estonian newsgroups'),
('eg', 'Egyptian newsgroups'),
('es', 'Spanish language newsgroups'),
('fi', 'Finnish language newsgroups'),
('fj', 'Japanese newsgroups (From Japan)'),
('fr', 'French language newsgroups'),
('gr', 'Greek language newsgroups'),
('hk', 'Hong Kong newsgroups'),
('hr', 'Croatian newsgroups'),
('hu', 'Hungarian newsgroups'),
('id', 'Indonesian newsgroups'),
('ie', 'Irish newsgroups'),
('il', 'Israeli newsgroups'),
('in', 'Indian newsgroups'),
('is', 'Icelandic newsgroups'),
('it', 'Italian language newsgroups'),
('jp', 'Japanese language newsgroups'),
('kr', 'Korean language newsgroups'),
('lt', 'Lithuanian newsgroups'),
('lu', 'Luxembourg newsgroups'),
('lv', 'Latvian newsgroups'),
('mx', 'Mexican newsgroups'),
('my', 'Malaysian newsgroups'),
('nl', 'Dutch/Netherlands newsgroups'),
('no', 'Norwegian language newsgroups'),
('nz', 'New Zealand newsgroups'),
('pe', 'Peruvian newsgroups'),
('ph', 'Philippine newsgroups'),
('pk', 'Pakistani newsgroups'),
('pl', 'Polish language newsgroups'),
('pt', 'Portuguese language newsgroups'),
('ro', 'Romanian newsgroups'),
('ru', 'Russian language newsgroups'),
('se', 'Swedish language newsgroups'),
('sg', 'Singapore newsgroups'),
('si', 'Slovenian newsgroups'),
('sk', 'Slovak language newsgroups'),
('th', 'Thai newsgroups'),
('tn', 'Tunisian newsgroups'),
('tr', 'Turkish language newsgroups'),
('tw', 'Taiwanese newsgroups'),
('ua', 'Ukrainian newsgroups'),
('uk', 'United Kingdom regional groups'),
('uy', 'Uruguayan newsgroups'),
('ve', 'Venezuelan newsgroups'),
('vn', 'Vietnamese newsgroups'),
('yu', 'Former Yugoslav newsgroups'),
('za', 'South African newsgroups'),

-- Regional US hierarchies (alphabetical)
('austin', 'Austin, Texas area'),
('az', 'Arizona regional groups'),
('ba', 'San Francisco Bay Area'),
('boston', 'Boston area'),
('ca', 'California regional groups'),
('chi', 'Chicago area'),
('co', 'Colorado regional groups'),
('ct', 'Connecticut regional groups'),
('dc', 'Washington DC area'),
('fl', 'Florida regional groups'),
('ga', 'Georgia regional groups'),
('hawaii', 'Hawaii regional groups'),
('houston', 'Houston area'),
('ia', 'Iowa regional groups'),
('il', 'Illinois regional groups'),
('in', 'Indiana regional groups'),
('ks', 'Kansas regional groups'),
('ky', 'Kentucky regional groups'),
('la', 'Los Angeles area'),
('ma', 'Massachusetts regional groups'),
('md', 'Maryland regional groups'),
('me', 'Maine regional groups'),
('mi', 'Michigan regional groups'),
('mn', 'Minnesota regional groups'),
('mo', 'Missouri regional groups'),
('ms', 'Mississippi regional groups'),
('mt', 'Montana regional groups'),
('nc', 'North Carolina regional groups'),
('nd', 'North Dakota regional groups'),
('ne', 'Nebraska regional groups'),
('nh', 'New Hampshire regional groups'),
('nj', 'New Jersey regional groups'),
('nm', 'New Mexico regional groups'),
('nv', 'Nevada regional groups'),
('ny', 'New York regional groups'),
('nyc', 'New York City area'),
('oh', 'Ohio regional groups'),
('ok', 'Oklahoma regional groups'),
('or', 'Oregon regional groups'),
('pa', 'Pennsylvania regional groups'),
('pdx', 'Portland area'),
('phila', 'Philadelphia area'),
('phoenix', 'Phoenix area'),
('pgh', 'Pittsburgh area'),
('ri', 'Rhode Island regional groups'),
('sc', 'South Carolina regional groups'),
('sd', 'South Dakota regional groups'),
('seattle', 'Seattle area'),
('stl', 'St. Louis area'),
('tenn', 'Tennessee regional groups'),
('triangle', 'Research Triangle area (NC)'),
('tx', 'Texas regional groups'),
('ut', 'Utah regional groups'),
('va', 'Virginia regional groups'),
('vt', 'Vermont regional groups'),
('wa', 'Washington state regional groups'),
('wi', 'Wisconsin regional groups'),
('wv', 'West Virginia regional groups'),
('wy', 'Wyoming regional groups'),

-- Special interest/alternative hierarchies (alphabetical)
('aioe', 'Aioe.org server newsgroups'),
('eternal-september', 'Eternal September server groups'),
('i2pn', 'I2P network newsgroups'),
('rocksolid', 'Rocksolid decentralized newsgroups'),
('tor', 'Tor network related groups'),

-- Technical/Computing (alphabetical)
('amiga', 'Amiga computers (legacy)'),
('android', 'Android development and usage'),
('apple', 'Apple products and technologies'),
('atari', 'Atari computers (legacy)'),
('beos', 'BeOS operating system (legacy)'),
('borland', 'Borland development tools'),
('bsd', 'BSD operating systems'),
('commodore', 'Commodore computers (legacy)'),
('debian', 'Debian Linux distribution'),
('dos', 'DOS operating systems'),
('fedora', 'Fedora Linux distribution'),
('freebsd', 'FreeBSD operating system'),
('gentoo', 'Gentoo Linux distribution'),
('gnu', 'GNU project and free software'),
('grc', 'Gibson Research Corporation'),
('ibm', 'IBM products and technologies'),
('linux', 'Linux operating system discussions'),
('mac', 'Macintosh computers and software'),
('mandriva', 'Mandriva Linux (legacy)'),
('microsoft', 'Microsoft products and technologies'),
('msdos', 'MS-DOS related (legacy)'),
('netbsd', 'NetBSD operating system'),
('novell', 'Novell products (legacy)'),
('openbsd', 'OpenBSD operating system'),
('oracle', 'Oracle database and products'),
('os2', 'OS/2 operating system (legacy)'),
('redhat', 'Red Hat Linux distribution'),
('sco', 'SCO Unix (legacy)'),
('sgi', 'Silicon Graphics (legacy)'),
('slackware', 'Slackware Linux distribution'),
('solaris', 'Solaris operating system'),
('sun', 'Sun Microsystems (legacy)'),
('suse', 'SUSE Linux distribution'),
('ubuntu', 'Ubuntu Linux distribution'),
('unix', 'Unix systems and variants'),
('vms', 'VMS operating system'),
('windows', 'Windows operating systems'),
('xenix', 'Xenix operating system (legacy)'),

-- Internet/Network related (alphabetical)
('aol', 'America Online groups'),
('compuserve', 'CompuServe groups (legacy)'),
('fidonet', 'FidoNet network groups'),
('inet', 'Internet service providers'),
('isp', 'ISP-specific newsgroups'),
('prodigy', 'Prodigy service (legacy)'),
('uunet', 'UUNET provider groups'),
('well', 'The WELL community'),

-- Educational institutions (alphabetical)
('berkeley', 'UC Berkeley newsgroups'),
('caltech', 'California Institute of Technology'),
('cmu', 'Carnegie Mellon University'),
('columbia', 'Columbia University'),
('cornell', 'Cornell University'),
('dartmouth', 'Dartmouth College'),
('duke', 'Duke University'),
('gatech', 'Georgia Tech'),
('harvard', 'Harvard University'),
('indiana', 'Indiana University'),
('jhu', 'Johns Hopkins University'),
('mit', 'MIT newsgroups'),
('msu', 'Michigan State University'),
('ncsu', 'North Carolina State University'),
('northwestern', 'Northwestern University'),
('nyu', 'New York University'),
('osu', 'Ohio State University'),
('princeton', 'Princeton University'),
('psu', 'Penn State University'),
('purdue', 'Purdue University'),
('rice', 'Rice University'),
('rutgers', 'Rutgers University'),
('stanford', 'Stanford University'),
('tamu', 'Texas A&M University'),
('ucb', 'UC Berkeley newsgroups'),
('ucla', 'UCLA newsgroups'),
('ucsb', 'UC Santa Barbara'),
('ucsd', 'UC San Diego'),
('ufl', 'University of Florida'),
('uiuc', 'University of Illinois'),
('umich', 'University of Michigan'),
('umn', 'University of Minnesota'),
('unc', 'University of North Carolina'),
('upenn', 'University of Pennsylvania'),
('usc', 'University of Southern California'),
('utexas', 'University of Texas'),
('uw', 'University of Washington'),
('virginia', 'University of Virginia'),
('vt', 'Virginia Tech'),
('wisc', 'University of Wisconsin'),
('wustl', 'Washington University in St. Louis'),
('yale', 'Yale University'),

-- Hobby/Interest groups (alphabetical)
('aquaria', 'Aquarium and fish keeping'),
('astro', 'Astronomy discussions'),
('auto', 'Automotive discussions'),
('aviation', 'Aviation and flying'),
('bicycles', 'Bicycle discussions'),
('birds', 'Bird watching and avian topics'),
('boats', 'Boating and marine topics'),
('cats', 'Cat-related discussions'),
('climbing', 'Rock climbing and mountaineering'),
('collecting', 'Collecting hobbies'),
('comics', 'Comic books and graphic novels'),
('crafts', 'Crafts and DIY projects'),
('dance', 'Dance discussions'),
('dogs', 'Dog-related discussions'),
('electronics', 'Electronics hobbyists'),
('equestrian', 'Horse riding and care'),
('film', 'Film and cinema discussions'),
('fitness', 'Fitness and exercise'),
('food', 'Food and cooking'),
('games', 'Computer and video games'),
('gardening', 'Gardening discussions'),
('genealogy', 'Family history research'),
('guns', 'Firearms discussions'),
('ham', 'Amateur radio discussions'),
('history', 'Historical discussions'),
('hunting', 'Hunting discussions'),
('martial-arts', 'Martial arts discussions'),
('military', 'Military topics'),
('models', 'Model building hobbies'),
('motorcycles', 'Motorcycle discussions'),
('mudding', 'MUD gaming discussions'),
('music', 'Music discussions'),
('outdoors', 'Outdoor activities'),
('pets', 'Pet care and discussions'),
('philosophy', 'Philosophical discussions'),
('photo', 'Photography discussions'),
('politics', 'Political discussions'),
('puzzles', 'Puzzles and brain teasers'),
('radio', 'Radio broadcasting topics'),
('railroads', 'Railroad enthusiasts'),
('religion', 'Religious discussions'),
('roguelike', 'Roguelike games'),
('running', 'Running and jogging'),
('scouting', 'Boy/Girl Scouts discussions'),
('scuba', 'Scuba diving'),
('skiing', 'Skiing and snowboarding'),
('space', 'Space exploration'),
('sport', 'Sports discussions'),
('stamps', 'Stamp collecting'),
('startrek', 'Star Trek fandom'),
('starwars', 'Star Wars fandom'),
('travel', 'Travel discussions'),
('tv', 'Television discussions'),
('video', 'Video production and editing'),
('wine', 'Wine appreciation'),
('woodworking', 'Woodworking projects'),

-- Corporate/Commercial (alphabetical)
('adobe', 'Adobe products discussions'),
('amazon', 'Amazon services discussions'),
('ap', 'Associated Press feeds'),
('autodesk', 'Autodesk products'),
('bbc', 'BBC news groups'),
('biz', 'Business and commercial discussions'),
('biz.marketplace', 'Commercial marketplace'),
('clari', 'ClariNet news service'),
('clarinet', 'Professional news service'),
('corel', 'Corel products discussions'),
('courts', 'Legal/court discussions'),
('ebay', 'eBay marketplace discussions'),
('google', 'Google products discussions'),
('govnews', 'Government news feeds'),
('intel', 'Intel products discussions'),
('lotus', 'Lotus products (legacy)'),
('market', 'Financial market discussions'),
('mozilla', 'Mozilla products discussions'),
('netscape', 'Netscape (legacy)'),
('nokia', 'Nokia products discussions'),
('novell', 'Novell products'),
('reuters', 'Reuters news feeds'),
('sybase', 'Sybase database products'),
('symantec', 'Symantec products'),
('vmware', 'VMware virtualization'),
('wordperfect', 'WordPerfect (legacy)'),
('xerox', 'Xerox products'),

-- Network gateways (alphabetical)
('bit', 'BITNET mailing list gateways'),
('bitnet', 'BITNET gateway groups'),
('fido', 'FidoNet gateways'),
('fido7', 'Fido7'),
('fidonet', 'FidoNet network discussions'),
('gateway', 'Gateway services'),
('lists', 'Mailing list gateways'),

-- Programming languages (alphabetical)
('ada', 'Ada programming language'),
('asm', 'Assembly language programming'),
('basic', 'BASIC programming language'),
('c', 'C programming language'),
('c++', 'C++ programming language'),
('clojure', 'Clojure programming language'),
('cobol', 'COBOL programming language'),
('dart', 'Dart programming language'),
('delphi', 'Delphi programming'),
('elixir', 'Elixir programming language'),
('erlang', 'Erlang programming language'),
('forth', 'Forth programming language'),
('fortran', 'Fortran programming language'),
('go', 'Go programming language'),
('groovy', 'Groovy programming language'),
('haskell', 'Haskell programming language'),
('java', 'Java programming language'),
('javascript', 'JavaScript programming'),
('julia', 'Julia programming language'),
('kotlin', 'Kotlin programming language'),
('lisp', 'Lisp programming language'),
('lua', 'Lua programming language'),
('matlab', 'MATLAB programming'),
('ml', 'ML programming languages'),
('modula', 'Modula programming languages'),
('nim', 'Nim programming language'),
('objective-c', 'Objective-C programming'),
('ocaml', 'OCaml programming language'),
('pascal', 'Pascal programming language'),
('perl', 'Perl programming language'),
('php', 'PHP programming language'),
('prolog', 'Prolog programming language'),
('python', 'Python programming language'),
('r', 'R programming language'),
('racket', 'Racket programming language'),
('ruby', 'Ruby programming language'),
('rust', 'Rust programming language'),
('scala', 'Scala programming language'),
('scheme', 'Scheme programming language'),
('smalltalk', 'Smalltalk programming'),
('swift', 'Swift programming language'),
('tcl', 'Tcl programming language'),
('typescript', 'TypeScript programming'),
('vb', 'Visual Basic programming'),
('verilog', 'Verilog hardware description'),
('vhdl', 'VHDL hardware description'),
('zig', 'Zig programming language'),

-- Academic/Research (alphabetical)
('aaai', 'AI research groups'),
('acm', 'ACM organization groups'),
('bioinformatics', 'Bioinformatics research'),
('biomed', 'Biomedical research'),
('chem', 'Chemistry discussions'),
('cognitive', 'Cognitive science'),
('comp-sci', 'Computer science research'),
('ecology', 'Ecology research'),
('eng', 'Engineering discussions'),
('genetics', 'Genetics research'),
('geology', 'Geology discussions'),
('ieee', 'IEEE organization groups'),
('linguistics', 'Linguistics research'),
('math', 'Mathematics discussions'),
('meteorology', 'Weather and climate science'),
('neuroscience', 'Neuroscience research'),
('physics', 'Physics discussions'),
('psychology', 'Psychology discussions'),
('robotics', 'Robotics research'),
('sociology', 'Sociology discussions'),
('statistics', 'Statistics discussions'),

-- Special purpose (alphabetical)
('answers', 'Q&A and FAQ postings'),
('bionet', 'Biology research network'),
('control', 'Control messages'),
('eunet', 'European network groups'),
('example', 'Example newsgroups for testing'),
('free', 'Free newsgroups hierarchy'),
('han', 'Korean Hangul newsgroups'),
('info', 'Information and announcements'),
('israel', 'Israeli national hierarchy'),
('japan', 'Japanese national hierarchy'),
('junk', 'Test messages'),
('k12', 'K-12 education groups'),
('local', 'Local server groups'),
('nzl', 'New Zealand local groups'),
('relcom', 'Former Soviet Union network'),
('school', 'School-related newsgroups'),
('test', 'Test postings'),
('to', 'Personal messages (legacy)'),
('tnn', 'The Network News'),
('usenet', 'USENET meta-discussions'),
('vmsnet', 'VMS network groups'),
('world', 'Worldwide discussions'),

-- Regional language variants (alphabetical)
('de.alt', 'German alternative groups'),
('de.comp', 'German computer groups'),
('de.rec', 'German recreational groups'),
('de.sci', 'German science groups'),
('de.soc', 'German social groups'),
('es.comp', 'Spanish computer groups'),
('es.rec', 'Spanish recreational groups'),
('fr.comp', 'French computer groups'),
('fr.rec', 'French recreational groups'),
('fr.sci', 'French science groups'),
('fr.soc', 'French social groups'),
('it.comp', 'Italian computer groups'),
('it.rec', 'Italian recreational groups'),
('it.sci', 'Italian science groups'),
('jp.comp', 'Japanese computer groups'),
('jp.rec', 'Japanese recreational groups'),
('nl.comp', 'Dutch computer groups'),
('nl.rec', 'Dutch recreational groups'),
('uk.comp', 'UK computer groups'),
('uk.rec', 'UK recreational groups'),
('uk.sci', 'UK science groups'),

-- Specialized networks (alphabetical)
('darknet', 'Darknet discussion groups'),
('freenet', 'Freenet network groups'),
('gopher', 'Gopher protocol groups'),
('i2p', 'I2P anonymous network'),
('onion', 'Tor onion network groups'),
('p2p', 'Peer-to-peer networking'),
('zer0net', 'Zer0net distributed groups'),

-- Defunct but historically important (alphabetical)
('arpa', 'ARPANET (historical)'),
('csnet', 'Computer Science Network (legacy)'),
('ddn', 'Defense Data Network (legacy)'),
('fa', 'From ARPANET (legacy)'),
('mod', 'Moderated groups (legacy)'),
('nato', 'NATO network (legacy)'),
('net', 'Original Internet hierarchy (legacy)'),
('pubnet', 'Public access network (legacy)'),
('uucp', 'UUCP network maps (legacy)');
